server:
  port: 20281
  servlet:
    context-path: /product-server
spring:
  application:
    name: config-product
  rabbitmq:
    host: 192.168.10.252
    port: 5672
    username: admin
    password: admin
    virtual-host: whportal
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
feign:
  okhttp:
    enabled: true
  client:
    config:
      default: # 服务名 填写default表示为所有服务 或者指定某个服务 如 order
        connectTimeout: 10000 # 连接超时 10秒
        readTimeout: 20000 # 读取超时 20秒
        loggerLevel: FULL
# 配置Eureka
ribbon:
  okhttp:
    enabled: true
product:
  config: Version 1.0.0 (PRO)